#!/bin/bash

theme=$HOME/.local/share/rofi/themes/run.rasi
ans=$(echo -e "turn display off (enter to turn back on)\nlock\nlogout\nsuspend\nhibernate\nreboot\nshutdown" | rofi -dmenu -theme $theme -p "PWR: ")

confirm_exit() {
    echo -e "no\nyes" | rofi -dmenu -theme $theme -p "Are you sure? " 
}

msg() {
    rofi -theme $theme -e "available options - yes/no/YES/NO/y/N"
}
case $ans in
    "shutdown")
		confirm=$(confirm_exit &)
		if [[ $confirm == "yes" || $confirm == "YES" || $confirm == "y" || $confirm == "Y" ]]; then
			shutdown now
		elif [[ $confirm == "no" || $confirm == "NO" || $confirm == "n" || $confirm == "N" ]]; then
			exit 0
        else
			msg
        fi
        ;;
    "reboot")
		confirm=$(confirm_exit &)
		if [[ $confirm == "yes" || $confirm == "YES" || $confirm == "y" || $confirm == "Y" ]]; then
			shutdown -r now
		elif [[ $confirm == "no" || $confirm == "NO" || $confirm == "n" || $confirm == "N" ]]; then
			exit 0
        else
			msg
        fi
        ;;
    "lock")
		betterlockscreen -l blur
        ;;
    "suspend")
		confirm=$(confirm_exit &)
		if [[ $confirm == "yes" || $confirm == "YES" || $confirm == "y" || $confirm == "Y" ]]; then
            playerctl -a pause
			systemctl suspend -i
		elif [[ $confirm == "no" || $confirm == "NO" || $confirm == "n" || $confirm == "N" ]]; then
			exit 0
        else
			msg
        fi
        ;;
    "hibernate")
		confirm=$(confirm_exit &)
		if [[ $confirm == "yes" || $confirm == "YES" || $confirm == "y" || $confirm == "Y" ]]; then
            betterlockscreen -l blur &
			systemctl hibernate -i
		elif [[ $confirm == "no" || $confirm == "NO" || $confirm == "n" || $confirm == "N" ]]; then
			exit 0
        else
			msg
        fi
        ;;
    "logout")
		confirm=$(confirm_exit &)
		if [[ $confirm == "yes" || $confirm == "YES" || $confirm == "y" || $confirm == "Y" ]]; then
			killall Hyprland
		elif [[ $confirm == "no" || $confirm == "NO" || $confirm == "n" || $confirm == "N" ]]; then
			exit 0
        else
			msg
        fi
        ;;
    "turn display off (enter to turn back on)")
		confirm=$(confirm_exit &)
		if [[ $confirm == "yes" || $confirm == "YES" || $confirm == "y" || $confirm == "Y" ]]; then
			/home/obey/.bins/disable_display
		elif [[ $confirm == "no" || $confirm == "NO" || $confirm == "n" || $confirm == "N" ]]; then
			exit 0
        else
			msg
        fi
        ;;
esac

